[versions]
kotlin = "2.1.20" # https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library
rdGen = "2025.3.1"
riderSdk = "2026.1-SNAPSHOT"
riderSdkPreview = "2026.1-SNAPSHOT"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
intelliJPlatform = "org.jetbrains.intellij.platform:2.10.4"
